### ISSUE TITLE
geoplugin responses without a city considered as not success

### ISSUE THREAD

**Issue by plashchynski** [geokit/geokit#161]
There's pretty valid responses without a city (a place can actually be outside of a city, isn't it?). But GeoPluginGeocoder considered such responses with blank city as not success. So MultiGeocoder returns nothing:

For example: http://www.geoplugin.net/xml.gp?ip=79.180.174.252

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<geoPlugin>
    <geoplugin_request>79.180.174.252</geoplugin_request>
    <geoplugin_status>206</geoplugin_status>
    <geoplugin_credit>Some of the returned data includes GeoLite data created by MaxMind, available from &lt;a href=\'http://www.maxmind.com\'&gt;http://www.maxmind.com&lt;/a&gt;.</geoplugin_credit>
    <geoplugin_city></geoplugin_city>
    <geoplugin_region></geoplugin_region>
    <geoplugin_areaCode>0</geoplugin_areaCode>
    <geoplugin_dmaCode>0</geoplugin_dmaCode>
    <geoplugin_countryCode>IL</geoplugin_countryCode>
    <geoplugin_countryName>Israel</geoplugin_countryName>
    <geoplugin_continentCode>AS</geoplugin_continentCode>
    <geoplugin_latitude>31.5</geoplugin_latitude>
    <geoplugin_longitude>34.75</geoplugin_longitude>
    <geoplugin_regionCode></geoplugin_regionCode>
    <geoplugin_regionName/>
    <geoplugin_currencyCode>ILS</geoplugin_currencyCode>
    <geoplugin_currencySymbol>&amp;#8362;</geoplugin_currencySymbol>
    <geoplugin_currencySymbol_UTF8>₪</geoplugin_currencySymbol_UTF8>
    <geoplugin_currencyConverter>3.9534</geoplugin_currencyConverter>
</geoPlugin>
```

``` ruby
>> Geokit::Geocoders::ip_provider_order
=> [:geo_plugin]
>> Geokit::Geocoders::MultiGeocoder.geocode('79.180.174.252') # returns an empty response
=> #<Geokit::GeoLoc:0x00000113c3c5f8 @all=[#<Geokit::GeoLoc:0x00000113c3c5f8 ...>], @street_address=nil, @sub_premise=nil, @street_number=nil, @street_name=nil, @city=nil, @state=nil, @state_code=nil, @state_name=nil, @zip=nil, @country_code=nil, @province=nil, @success=false, @precision="unknown", @full_address=nil, @lat=nil, @lng=nil>
>> result = Geokit::Geocoders::GeoPluginGeocoder.geocode('79.180.174.252') # returns a good response
=> #<Geokit::GeoLoc:0x000001149958d0 @all=[#<Geokit::GeoLoc:0x000001149958d0 ...>], @street_address=nil, @sub_premise=nil, @street_number=nil, @street_name=nil, @city=nil, @state=nil, @state_code=nil, @state_name=nil, @zip=nil, @country_code="IL", @province=nil, @success=false, @precision="unknown", @full_address=nil, @lat=31.5, @lng=34.75, @provider="geo_plugin">
>> response.success?
=> false
```

I suggest to use `countryCode` to determine success of geoplugin responses.

**Comment by mnoack** [comment]
Sorry @plashchynski for not responding sooner. Can you make a PR to change it to the desired behavior?

You can change the success setter in this file:
https://github.com/geokit/geokit/blob/master/lib/geokit/geocoders/geo_plugin.rb

Please also see the history of that file to see if there was any reason as to why this was deemed a success or not.

I'm also tempted to apply the same common-sense logic you made to all geocoders, because I agree that even something like a country can give "rough" co-ordinates for useful purposes, e.g. an app that say s "what's the distance between X and Y". Someone may say "United States" and "Europe", and whilst that might not be as accurate as "New York" and "Madrid" it's still going to give a reasonable answer.

**Comment by ryankopf** [comment]
Closing issue as it's been so long and there have been many changes in the code since this comment. If you see this as still being an issue, or experience any other bugs, please open a new issue or submit a PR. Thank you.
