### ISSUE TITLE
Geokit::Geocoders::AccessDeniedError: This API project is not authorized to use this API. Please ensure that this API is activated in the APIs Console

### ISSUE THREAD

**Issue by wenwei63029869** [geokit/geokit#179]
@mnoackl, I kept getting this error in my  rails console when I called          

       Geokit::Geocoders::GoogleGeocoder.geocode('140 Market St, San Francisco, CA')

. I required the gem and make sure my api key is enabled. I also tested my API key by making HTTP request and it returned a correct result. I am using rails 4.2.4 and Ruby 2.2.1. What do I need to do to fix this issue? Thanks.

**Comment by geermc4** [comment]
Need to enable access to the API https://console.developers.google.com/apis/library

**Comment by mnoack** [comment]
Sorry @wenwei63029869 - Sometimes in my busy days these things get forgotten. What was the error. I tried that code in a blank project and it failed with an older geokit (due to SSL not being required) but was fine in a new project (no key or anything)

If you can provide a test project with minimal code (ideally only 1 file) that would really help me to replicate and fix the issue.

Thanks @geermc4 for the suggestion and hopefully that solved the issue.

**Comment by mnoack** [comment]
Sorry, missed the issue title (I went straight for the content of your message, doh!)
