### ISSUE TITLE
gem distance_from result is différent from google map

### ISSUE THREAD

**Issue by alain-andre** [geokit/geokit#190]
Hi there, I'm having an issue with `distance_from`. Probably because I'm not yet an expert of your awesome gem.

When I ask google map the distance from  *44.841156, -0.578363* to *43.604408, 1.440736* it gives me 245 kms.

When I use the gem with the same lat/lng `self.origin.distance_from(self.destination) / 0.0010000` it gives me 210,46 Kms.

Here is my `geokit_config.rb`.
```ruby
Geokit::default_units = :kms # others :kms, :nms, :meters
Geokit::default_formula = :flat
Geokit::Geocoders::request_timeout = 3
Geokit::Geocoders::provider_order = [:google,:us]
```

What could I do to get the same Kms ?

**Comment by mnoack** [comment]
Have your tried removing default_formula which does spherical normally?

**Comment by alain-andre** [comment]
Hi, @mnoack . Yes I tried spherical, it gives me 211,83 Kms.

**Comment by lmoncany** [comment]
Up

**Comment by oricodes89** [comment]
Up

**Comment by mnoack** [comment]
So 245km is the driving distance, which is because whilst the distance between two points is 211km (confirmed with http://www.movable-type.co.uk/scripts/latlong.html), the driving path between those points is not very straight at all.

Spherical is the more accurate (especially as the distance gets longer)

**Comment by mnoack** [comment]
@alain-andre @oricodes89 @lmoncany Answer above.
