### ISSUE TITLE
Bias not working correctly

### ISSUE THREAD

**Issue by dougc84** [geokit/geokit#203]
I have an issue on a site I work on that doesn't play nicely with Geokit.  There are a couple things here for improvement.

We want to limit responses to US, Canada, and other US territories.  The `components` option of the `GoogleGeocoder` only allows 1 `country` option, whereas the API can take something like the following:

`https://...country:us|country:ca|country:vi`

It'd be nice to see the country option implemented as accepting an array.

However, trying out the `bias` option doesn't meet our needs either.  If someone types in "st petersburg", they're wanting St. Petersburg, FL.  Even with the bias option (I'm confused by the documentation whether its "US" or "com", though I've tried both), we get back St. Petersburg, Russia.

Thankfully, we cache all calls and we can modify the cache, but something's not working quite right here.

Thanks!

**Comment by mnoack** [comment]
@dougc84 I've got no objections to you making a patch to the code.
It would be a new option (like bounding box) to lib/geokit/geocoders/google.rb

Then write a test (see test folder for google test), you should be able to follow the format and do a simple PR.

**Comment by dougc84** [comment]
@mnoack I wrote an issue because I work 40+ hours a week and don't have time to patch the code here.  Thanks for closing an issue that is a perfectly valid bug.

**Comment by gambala** [comment]
@mnoack, same bug, bias option doesn't affect on search results. Why this issue is still closed?

**Comment by mnoack** [comment]
@gambala I closed it as I'm trying to avoid having 100's of open issues. That isn't me saying the issues isn't solved, but that a response has been given.

@dougc84 I'm in the same boat (I work 40+ hours a week and don't have time to patch a lot of bugs I find in other projects).

Before I joined geokit there was lots of fixes already patched, but not being merged, because like both of us project maintainers work 40+ hours a week and don't have time to patch.

My intent as maintainer in geokit is to ensure that if PR's are made, I will do my best to merge or decline them promptly and state reasons why. That is a great improvement on a no longer maintained project but I agree that it's not idea, but then I'm not being paid either.

Possible resolutions are:
1) Submit a PR
2) Patch the bug locally (maybe @gambala can provide his code)
3) Use a more maintained library (geocoder is one of the other popular gems around)
4) Post a bounty to have the fix made - I may not fix it, but with a bounty others may be interested - https://www.bountysource.com/teams/geokit/issues
