### ISSUE TITLE
Geokit breaks Rails 3 ActiveRecord logging

### ISSUE THREAD

**Issue by kevinmtrowbridge** [geokit/geokit#30]
Kind of a subtle bug but I noticed that I had to call Rails.logger.debug, for example, instead of just logger.debug, when in ActiveRecord classes.  I also wasn't getting any query-logging in my development.log ... (the blue and pink statements).

Looking into it further I noticed that if I commented out the Geokit gem, it started working again.

I was doing this in one of my observers -- as the documentation states:
include Geokit::Geocoders

This somehow was causing the ActiveRecord::Base.logger to be set to a Logger.new(STDOUT) object.  Anyways, I removed the include statement and accessed the Geocoder using the full namespace like so:

Geokit::Geocoders::GoogleGeocoder.geocode(...)

... and this reenabled the ActiveRecord logging.

Probably useful for others to know, and good to fix when you get it updated for Rails 3.

**Comment by ryankopf** [comment]
Closing issue as it's been so long and there have been many changes in the code since this comment. I don't believe Geokit modifies the existing logger in the code, it appears to call Logger.new. If you see this as still being an issue, or experience any other bugs, please open a new issue or submit a PR. Thank you.
